name: Schedule GHCR Image Cleanup

on:
  workflow_dispatch:

  schedule:
    - cron: "0 07 * * 0"

permissions:
  pull-requests: write # add PR comment
  packages: write

jobs:
  delete_packages:
    name: delete packages
    runs-on: ubuntu-latest
    steps:
      - name: Get package id
        uses: castlabs/get-package-version-id-action@v2.0
        id: version
        with:
          version: "pr-1234"
      - name: Delete old cardiolib PR images
        uses: actions/delete-package-versions@v5
        if: ${{ steps.version.outputs.ids != '' }}
        with:
          package-version-ids: "${{ steps.versions.outputs.ids }}"
      # - name: Delete old cardiolib PR images main
      #   uses: actions/delete-package-versions@v5
      #   with:
      #     package-name: 'cardiolib'
      #     package-type: 'container'
      #     min-versions-to-keep: 3
      #     ignore-versions: '^(2\.3.\.0)$', '^(2\.19.)$'
