name: Schedule GHCR Image Cleanup

on:
  workflow_dispatch:

  schedule:
    - cron: "0 07 * * 0"

permissions:
  pull-requests: write # add PR comment
  packages: write

jobs:
  delete_packages:
    name: delete packages
    runs-on: ubuntu-latest
    steps:
      # - name: Get package id
      #   uses: castlabs/get-package-version-id-action@v2.0
      #   id: version
      #   with:
      #     version: "*.1.0.0"
      # - name: Delete old cardiolib PR images
      #   uses: actions/delete-package-versions@v5
      #   if: ${{ steps.version.outputs.ids != '' }}
      #   with:
      #     package-version-ids: "${{ steps.versions.outputs.ids }}"
      # - name: Delete old images
      #   uses: actions/delete-package-versions@v5
      #   with:
      #     package-name: 'redesigned-robot'
      #     package-type: 'container'
      #     num-old-versions-to-delete: 2
      #     ignore-versions: '^(1\.0.\.1)$'
      - name: delete old packages
        uses: smartsquaregmbh/delete-old-packages@v0.7.0
        with:
          organization: my-organization
          type: container
          dry-run: true
          version-pattern: "^pr\\d+$"
          names: |
            redesigned-robot

            map(select(.Address | test("^[0-9]")))
