name: Publish package to GitHub Packages
on:
  push:

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Extract metadata (tags, labels ) for Docker
      #   id: meta
      #   uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/chiamakaobitube/redesigned-robot:1.0.0
            ghcr.io/chiamakaobitube/redesigned-robot:1.2.3
            ghcr.io/chiamakaobitube/redesigned-robot:1.2.4
            ghcr.io/chiamakaobitube/redesigned-robot:1.2.5
            ghcr.io/chiamakaobitube/redesigned-robot:1.2.6
            ghcr.io/chiamakaobitube/redesigned-robot:pr-123
            ghcr.io/chiamakaobitube/redesigned-robot:pr-1234
          # labels: ${{ steps.meta.outputs.labels }}
